function COMfinal2 = COMfinal2(in1)
%COMFINAL2
%    COMFINAL2 = COMFINAL2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    14-Apr-2022 10:31:55

q5 = in1(5,:);
COMfinal2 = [cos(q5).*2.889461123941494e-1;sin(q5).*(-2.889461123941494e-1);-9.0./1.0e+2];
