function H_i = from_DH_to_H(in1)
%FROM_DH_TO_H
%    H_I = FROM_DH_TO_H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    16-Nov-2021 08:44:44

alphax_i = in1(:,4);
ax_i = in1(:,3);
dz_i = in1(:,2);
thetaz_i = in1(:,1);
t2 = cos(alphax_i);
t3 = sin(alphax_i);
t4 = cos(thetaz_i);
t5 = sin(thetaz_i);
H_i = reshape([t4,t5,0.0,0.0,-t2.*t5,t2.*t4,t3,0.0,t3.*t5,-t3.*t4,t2,0.0,ax_i.*t4,ax_i.*t5,dz_i,1.0],[4,4]);
