function [d,pos] = func_sym_arm_kinematics_3D(in1)
%FUNC_SYM_ARM_KINEMATICS_3D
%    [D,POS] = FUNC_SYM_ARM_KINEMATICS_3D(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    14-Apr-2022 10:32:19

q1 = in1(1,:);
q2 = in1(2,:);
q4 = in1(4,:);
q5 = in1(5,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q5);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q5);
t8 = pi./2.0;
t9 = q4+t8;
t10 = t6.*(1.2e+1./2.5e+1);
t14 = t2.*t3.*(1.2e+1./2.5e+1);
t15 = t3.*t5.*(1.2e+1./2.5e+1);
t16 = t4.*t6.*(3.3e+1./1.0e+2);
t21 = t2.*t3.*t4.*(3.3e+1./1.0e+2);
t22 = t3.*t4.*t5.*(3.3e+1./1.0e+2);
t11 = cos(t9);
t12 = sin(t9);
t13 = -t10;
t19 = -t16;
t17 = t2.*t12;
t18 = t5.*t12;
t20 = t5.*t6.*t11;
t23 = t2.*t6.*t11;
t24 = (t2.*t11)./5.0;
t25 = (t5.*t11)./5.0;
t26 = (t3.*t12)./5.0;
t33 = t2.*t11.*(9.0./1.0e+2);
t35 = t5.*t11.*(9.0./1.0e+2);
t36 = t3.*t12.*(9.0./1.0e+2);
t41 = t3.*t7.*t11.*(3.3e+1./1.0e+2);
t27 = -t20;
t28 = -t24;
t29 = -t26;
t30 = (t6.*t17)./5.0;
t31 = (t6.*t18)./5.0;
t37 = -t33;
t38 = -t36;
t39 = t6.*t17.*(9.0./1.0e+2);
t40 = t6.*t18.*(9.0./1.0e+2);
t44 = t18+t23;
t32 = -t30;
t34 = -t31;
t42 = -t39;
t43 = -t40;
t45 = t17+t27;
t46 = t7.*t44.*(3.3e+1./1.0e+2);
t49 = t13+t19+t29+t41;
t47 = t7.*t45.*(3.3e+1./1.0e+2);
t50 = t14+t21+t25+t32+t46;
t48 = -t47;
t51 = t15+t22+t28+t34+t48;
d = [t50;t51;t49];
if nargout > 1
    pos = reshape([0.0,0.0,0.0,0.0,0.0,0.0,t14,t15,t13,t14+t35+t42,t15+t37+t43,t13+t38,t14+t21+t35+t42+t46,t15+t22+t37+t43+t48,t13+t19+t38+t41,t50,t51,t49],[3,6]);
end
