function angleFinal = sym_arm_cg(in1)
%SYM_ARM_CG
%    ANGLEFINAL = SYM_ARM_CG(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    11-Jan-2022 10:18:04

q2 = in1(2,:);
q4 = in1(4,:);
q5 = in1(5,:);
t2 = cos(q2);
t3 = cos(q5);
t4 = sin(q2);
t5 = sin(q5);
t6 = pi./2.0;
t7 = q4+t6;
t8 = cos(t7);
t9 = sin(t7);
et1 = t2.*3.020271971795518e-1+t4.*3.020271971795518e-1i+t2.*t3.*9.452052379753213e-2+t3.*t4.*9.452052379753213e-2i+t2.*t9.*2.944094686476958e-2i;
et2 = t4.*t9.*(-2.944094686476958e-2)-t2.*t5.*t8.*9.452052379753213e-2i+t4.*t5.*t8.*9.452052379753213e-2;
angleFinal = angle(et1+et2);
