function radiusFinal2 = radiusFinal2(in1)
%RADIUSFINAL2
%    RADIUSFINAL2 = RADIUSFINAL2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    14-Apr-2022 10:31:55

q5 = in1(5,:);
radiusFinal2 = sqrt(cos(q5).^2.*8.348985586769242e-2+sin(q5).^2.*8.348985586769242e-2);
