function J = sym_arm_jacobian(in1)
%SYM_ARM_JACOBIAN
%    J = SYM_ARM_JACOBIAN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    31-Aug-2021 14:10:00

q1 = in1(1,:);
q2 = in1(2,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = sin(t4);
t8 = t3.*(3.0./1.0e+1);
t9 = t5.*(3.0./1.0e+1);
t10 = -t9;
t11 = t6.*(3.0./1.0e+1);
t12 = t7.*(3.0./1.0e+1);
t13 = -t12;
J = reshape([t10+t13-sin(q1).*(3.0./1.0e+1),t8+t11+cos(q1).*(3.0./1.0e+1),0.0,t10+t13,t8+t11,0.0,t13,t11,0.0],[3,3]);
