function R3 = sym_R3(th)
%SYM_R3
%    R3 = SYM_R3(TH)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    29-Aug-2021 17:10:45

t2 = cos(th);
t3 = sin(th);
R3 = reshape([t2,t3,0.0,-t3,t2,0.0,0.0,0.0,1.0],[3,3]);
