function R1 = sym_R1(th)
%SYM_R1
%    R1 = SYM_R1(TH)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    29-Aug-2021 17:10:45

t2 = cos(th);
t3 = sin(th);
R1 = reshape([1.0,0.0,0.0,0.0,t2,t3,0.0,-t3,t2],[3,3]);
