function angleFinal = angleFinal_round(in1)
%ANGLEFINAL_ROUND
%    ANGLEFINAL = ANGLEFINAL_ROUND(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    26-Mar-2022 08:53:24

q2 = in1(2,:);
q4 = in1(4,:);
q5 = in1(5,:);
t2 = cos(q2);
t3 = cos(q5);
t4 = sin(q2);
t5 = sin(q5);
t6 = pi./2.0;
t7 = -t6;
t8 = q4+t7;
t9 = cos(t8);
t10 = sin(t8);
et1 = t2.*3.519923926824851e-1+t4.*3.519923926824851e-1i+t2.*t3.*1.606305017207028e-1+t3.*t4.*1.606305017207028e-1i-t2.*t10.*1.03205940952726e-1i;
et2 = t4.*t10.*1.03205940952726e-1+t2.*t5.*t9.*1.606305017207028e-1i-t4.*t5.*t9.*1.606305017207028e-1;
angleFinal = angle(et1+et2);
