function d_02 = d_02(in1)
%D_02
%    D_02 = D_02(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    29-Nov-2021 16:01:21

q1 = in1(1,:);
d_02 = [cos(q1).*(2.1e+1./2.0e+2);sin(q1).*(2.1e+1./2.0e+2);4.7e+1./4.0e+2];
