function T_i = from_DH_to_T(in1)
%FROM_DH_TO_T
%    T_I = FROM_DH_TO_T(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    27-Aug-2021 11:41:05

alphax_i = in1(:,4);
ax_i = in1(:,3);
dz_i = in1(:,2);
thetaz_i = in1(:,1);
t2 = cos(alphax_i);
t3 = sin(alphax_i);
t4 = cos(thetaz_i);
t5 = sin(thetaz_i);
T_i = reshape([t4,t5,0.0,0.0,-t2.*t5,t2.*t4,t3,0.0,t3.*t5,-t3.*t4,t2,0.0,ax_i.*t4,ax_i.*t5,dz_i,1.0],[4,4]);
