function [d,pos] = func_sym_arm_kinematics_3D(in1)
%FUNC_SYM_ARM_KINEMATICS_3D
%    [D,POS] = FUNC_SYM_ARM_KINEMATICS_3D(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    19-Jan-2022 11:31:30

q1 = in1(1,:);
q2 = in1(2,:);
q4 = in1(4,:);
q5 = in1(5,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q5);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q5);
t8 = pi./2.0;
t9 = -t8;
t10 = t6.*(1.2e+1./2.5e+1);
t15 = t2.*t3.*(1.2e+1./2.5e+1);
t16 = t3.*t5.*(1.2e+1./2.5e+1);
t17 = t4.*t6.*(3.3e+1./1.0e+2);
t21 = t2.*t3.*t4.*(3.3e+1./1.0e+2);
t22 = t3.*t4.*t5.*(3.3e+1./1.0e+2);
t11 = q4+t9;
t12 = -t10;
t18 = -t17;
t13 = cos(t11);
t14 = sin(t11);
t19 = t2.*t14;
t20 = t5.*t14;
t23 = t5.*t6.*t13;
t24 = t2.*t6.*t13;
t25 = (t2.*t13)./5.0;
t26 = (t5.*t13)./5.0;
t27 = (t3.*t14)./5.0;
t32 = t3.*t7.*t13.*(3.3e+1./1.0e+2);
t28 = -t23;
t29 = -t26;
t30 = (t6.*t19)./5.0;
t31 = (t6.*t20)./5.0;
t33 = -t32;
t34 = t20+t24;
t35 = t19+t28;
t36 = t7.*t34.*(3.3e+1./1.0e+2);
t39 = t12+t18+t27+t33;
t37 = -t36;
t38 = t7.*t35.*(3.3e+1./1.0e+2);
t40 = t15+t21+t29+t30+t37;
t41 = t16+t22+t25+t31+t38;
d = [t40;t41;t39];
if nargout > 1
    pos = reshape([0.0,0.0,0.0,0.0,0.0,0.0,t15,t16,t12,t15+t21+t37-t5.*t13.*(9.0./1.0e+2)+t6.*t19.*(9.0./1.0e+2),t16+t22+t38+t2.*t13.*(9.0./1.0e+2)+t6.*t20.*(9.0./1.0e+2),t12+t18+t33+t3.*t14.*(9.0./1.0e+2),t40,t41,t39],[3,5]);
end
