function radiusFinal = radiusFinal(in1)
%RADIUSFINAL
%    RADIUSFINAL = RADIUSFINAL(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    19-Jan-2022 13:07:18

q2 = in1(2,:);
q4 = in1(4,:);
q5 = in1(5,:);
t2 = cos(q2);
t3 = cos(q5);
t4 = sin(q2);
t5 = sin(q5);
t6 = pi./2.0;
t7 = -t6;
t8 = q4+t7;
t9 = cos(t8);
t10 = sin(t8);
et1 = (t2.*3.020271971795518e-1+t2.*t3.*9.452052379753213e-2+t4.*t10.*6.542432636615462e-2-t4.*t5.*t9.*9.452052379753213e-2).^2;
et2 = (t4.*3.020271971795518e-1+t3.*t4.*9.452052379753213e-2-t2.*t10.*6.542432636615462e-2+t2.*t5.*t9.*9.452052379753213e-2).^2;
radiusFinal = sqrt(et1+et2);
