function [d_04,position] = sym_arm_kinematics_3D(in1)
%SYM_ARM_KINEMATICS_3D
%    [D_04,POSITION] = SYM_ARM_KINEMATICS_3D(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    07-Jan-2022 10:18:55

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = t2.*(2.1e+1./2.0e+2);
t9 = t2.*(3.9e+1./2.0e+2);
t10 = t6.*(3.3e+1./1.0e+2);
t11 = t5.*(2.1e+1./2.0e+2);
t12 = t5.*(3.9e+1./2.0e+2);
t13 = t2.*t3.*(3.3e+1./1.0e+2);
t14 = t3.*t5.*(3.3e+1./1.0e+2);
t15 = t3.*t7.*(6.3e+1./2.0e+2);
t16 = t4.*t6.*(6.3e+1./2.0e+2);
t18 = t5.*t6.*t7.*(6.3e+1./2.0e+2);
t19 = t2.*t3.*t4.*(6.3e+1./2.0e+2);
t20 = t3.*t4.*t5.*(6.3e+1./2.0e+2);
t21 = t2.*t6.*t7.*(6.3e+1./2.0e+2);
t17 = -t14;
t22 = -t20;
t23 = -t21;
t24 = t10+t15+t16+4.7e+1./4.0e+2;
t25 = t12+t13+t19+t23;
t26 = t9+t17+t18+t22;
d_04 = [t26;t25;t24];
if nargout > 1
    position = reshape([0.0,0.0,0.0,t8,t11,4.7e+1./4.0e+2,t8,t11,4.7e+1./4.0e+2,t9+t17,t12+t13,t10+4.7e+1./4.0e+2,t26,t25,t24],[3,5]);
end
