function [d_03,position] = sym_arm_kinematics(in1)
%SYM_ARM_KINEMATICS
%    [D_03,POSITION] = SYM_ARM_KINEMATICS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    02-Sep-2021 10:01:55

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = q1+q2;
t7 = cos(t6);
t8 = q3+t6;
t9 = sin(t6);
t12 = t2.*(3.0./1.0e+1);
t13 = t4.*(3.0./1.0e+1);
t10 = cos(t8);
t11 = sin(t8);
t14 = t7.*(3.0./1.0e+1);
t15 = t9.*(3.0./1.0e+1);
t16 = t10.*(3.0./1.0e+1);
t17 = t11.*(3.0./1.0e+1);
t18 = t12+t14+t16;
t19 = t13+t15+t17;
d_03 = [t18;t19;4.7e+1./2.0e+2];
if nargout > 1
    position = reshape([0.0,0.0,0.0,t12,t13,1.3e+1./2.0e+2,t12-t4.*t5.*(3.0./1.0e+1)+t3.*t12,t13+t3.*t13+t5.*t12,3.0./2.0e+1,t18,t19,4.7e+1./2.0e+2],[3,4]);
end
