function J = sym_arm_jacobian_3D(in1)
%SYM_ARM_JACOBIAN_3D
%    J = SYM_ARM_JACOBIAN_3D(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    07-Jan-2022 10:18:56

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = q2+q3;
t9 = cos(t8);
t10 = sin(t8);
t11 = t6.*2.2e+1;
t12 = t10.*2.1e+1;
t13 = t9.*(6.3e+1./2.0e+2);
t14 = t11+t12;
J = reshape([t5.*(-3.9e+1./2.0e+2)-t2.*t3.*(3.3e+1./1.0e+2)-t2.*t3.*t4.*(6.3e+1./2.0e+2)+t2.*t6.*t7.*(6.3e+1./2.0e+2),t2.*(3.9e+1./2.0e+2)-t3.*t5.*(3.3e+1./1.0e+2)-t3.*t4.*t5.*(6.3e+1./2.0e+2)+t5.*t6.*t7.*(6.3e+1./2.0e+2),0.0,t5.*t14.*(3.0./2.0e+2),t2.*t14.*(-3.0./2.0e+2),t3.*(3.3e+1./1.0e+2)+t13,t5.*t10.*(6.3e+1./2.0e+2),t2.*t10.*(-6.3e+1./2.0e+2),t13],[3,3]);
